dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
script:
  - gcc -v && g++ -v && cmake --version
  - cmake .
  - make
  - make check
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install libboost-all-dev libpion-dev
